# Generated by Django 4.0.6 on 2022-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Car name')),
                ('about', models.TextField(verbose_name='Car about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Car image')),
                ('price', models.IntegerField(verbose_name='Car price')),
            ],
        ),
    ]
